set_property -dict {PACKAGE_PIN M4 IOSTANDARD LVCMOS33} [get_ports a]
set_property -dict {PACKAGE_PIN N4 IOSTANDARD LVCMOS33} [get_ports b]
set_property -dict {PACKAGE_PIN R1 IOSTANDARD LVCMOS33} [get_ports cin]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports sum]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports cout]